const weatherCodes = [
  {
    id: 200,
    Main: "Thunderstorm",
    Description: "thunderstorm with light rain",
    Icon: "11d",
  },
  {
    id: 201,
    Main: "Thunderstorm",
    Description: "thunderstorm with rain",
    Icon: "11d",
  },
  {
    id: 202,
    Main: "Thunderstorm",
    Description: "thunderstorm with heavy rain",
    Icon: "11d",
  },
  {
    id: 210,
    Main: "Thunderstorm",
    Description: "light thunderstorm",
    Icon: "11d",
  },
  {
    id: 211,
    Main: "Thunderstorm",
    Description: "thunderstorm",
    Icon: "11d",
  },
  {
    id: 212,
    Main: "Thunderstorm",
    Description: "heavy thunderstorm",
    Icon: "11d",
  },
  {
    id: 221,
    Main: "Thunderstorm",
    Description: "ragged thunderstorm",
    Icon: "11d",
  },
  {
    id: 230,
    Main: "Thunderstorm",
    Description: "thunderstorm with light drizzle",
    Icon: "11d",
  },
  {
    id: 231,
    Main: "Thunderstorm",
    Description: "thunderstorm with drizzle",
    Icon: "11d",
  },
  {
    id: 232,
    Main: "Thunderstorm",
    Description: "thunderstorm with heavy drizzle",
    Icon: "11d",
  },
  {
    id: 300,
    Main: "Drizzle",
    Description: "light intensity drizzle",
    Icon: "09d",
  },
  {
    id: 301,
    Main: "Drizzle",
    Description: "drizzle ",
    Icon: "09d",
  },
  {
    id: 302,
    Main: "Drizzle",
    Description: "heavy intensity drizzle",
    Icon: "09d",
  },
  {
    id: 310,
    Main: "Drizzle",
    Description: "light intensity drizzle rain ",
    Icon: "09d",
  },
  {
    id: 311,
    Main: "Drizzle",
    Description: "drizzle rain ",
    Icon: "09d",
  },
  {
    id: 312,
    Main: "Drizzle",
    Description: "light intensity drizzle rain ",
    Icon: "09d",
  },
  {
    id: 313,
    Main: "Drizzle",
    Description: "shower rain and drizzle",
    Icon: "09d",
  },
  {
    id: 321,
    Main: "Drizzle",
    Description: "shower drizzle",
    Icon: "09d",
  },
  {
    id: 500,
    Main: "Rain",
    Description: "light rain",
    Icon: "10d",
  },
  {
    id: 501,
    Main: "Rain",
    Description: "moderate rain",
    Icon: "10d",
  },
  {
    id: 502,
    Main: "Rain",
    Description: "heavy intensity rain",
    Icon: "10d",
  },
  {
    id: 503,
    Main: "Rain",
    Description: "very heavy rain",
    Icon: "10d",
  },
  {
    id: 504,
    Main: "Rain",
    Description: "extreme rain",
    Icon: "10d",
  },
  {
    id: 511,
    Main: "Rain",
    Description: "freezing rain",
    Icon: "13d",
  },
  {
    id: 520,
    Main: "Rain",
    Description: "light intensity shower rain",
    Icon: "09d",
  },
  {
    id: 521,
    Main: "Rain",
    Description: "shower rain",
    Icon: "09d",
  },
  {
    id: 522,
    Main: "Rain",
    Description: "heavy intensity shower rain",
    Icon: "09d",
  },
  {
    id: 531,
    Main: "Rain",
    Description: "ragged shower rain",
    Icon: "09d",
  },
  {
    id: 600,
    Main: "Snow",
    Description: "light snow",
    Icon: "13d",
  },
  {
    id: 601,
    Main: "Snow",
    Description: "snow",
    Icon: "13d",
  },
  {
    id: 602,
    Main: "Snow",
    Description: "heavy snow",
    Icon: "13d",
  },
  {
    id: 611,
    Main: "Snow",
    Description: "sleet",
    Icon: "13d",
  },
  {
    id: 612,
    Main: "Snow",
    Description: "light shower sleet",
    Icon: "13d",
  },
  {
    id: 613,
    Main: "Snow",
    Description: "shower sleet",
    Icon: "13d",
  },
  {
    id: 615,
    Main: "Snow",
    Description: "light rain and snow",
    Icon: "13d",
  },
  {
    id: 616,
    Main: "Snow",
    Description: "rain and snow",
    Icon: "13d",
  },
  {
    id: 620,
    Main: "Snow",
    Description: "light shower snow",
    Icon: "13d",
  },
  {
    id: 621,
    Main: "Snow",
    Description: "shower snow",
    Icon: "13d",
  },
  {
    id: 622,
    Main: "Snow",
    Description: "heavy shower snow",
    Icon: "13d",
  },
  {
    id: 701,
    Main: "Mist",
    Description: "mist",
    Icon: "50d",
  },
  {
    id: 711,
    Main: "Smoke",
    Description: "smoke",
    Icon: "50d",
  },
  {
    id: 721,
    Main: "Haze",
    Description: "haze",
    Icon: "50d",
  },
  {
    id: 731,
    Main: "Dust",
    Description: "sand/dust whirls",
    Icon: "50d",
  },
  {
    id: 741,
    Main: "Fog",
    Description: "Fog",
    Icon: "50d",
  },
  {
    id: 751,
    Main: "Sand",
    Description: "sand",
    Icon: "50d",
  },
  {
    id: 761,
    Main: "Dust",
    Description: "dust",
    Icon: "50d",
  },
  {
    id: 762,
    Main: "Ash",
    Description: "volcanic ash",
    Icon: "50d",
  },
  {
    id: 771,
    Main: "Squail",
    Description: "squalls",
    Icon: "50d",
  },
  {
    id: 781,
    Main: "Tornado",
    Description: "tornado",
    Icon: "50d",
  },
  {
    id: 800,
    Main: "Clear",
    Description: "clear sky",
    Icon: "01d",
  },
  {},
];
